sudo: required
services:
  - docker

before_install:
  - docker build -t abdurrehman245/docker-react -f Dockerfile.dev .

scripts:
  - docker run abdurrehman245/docker-react npm run test -- --coverage
